"""extentions for grading_schemas with fks

Revision ID: 4baef00d99cf
Revises: 0410a72f5ce0
Create Date: 2026-04-07 20:34:25.376176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4baef00d99cf"
down_revision: Union[str, Sequence[str], None] = "0410a72f5ce0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
